### PR TITLE
Fix mpi build issue

### PR DESCRIPTION
**Pull request by rschutt**

### CODE REVIEW

**Comment by rschutt** [comment]
This is untested.  Hopefully this fixes the MPI issue with this scidb image.  I'll try to test this out on Monday.

**Comment by rvernica** [comment]
Are you referring to this issue from the `Dockerfile.pre` build log:

```
-- ****************** BEGIN src/mpi/CMakeLists.txt ******************
-- WARNING-- using locally installed MPICH2 
-- Local MPICH2 path: UNDEFINED_FOR_THIS_PLATFORM 
-- WARNING-- using locally installed ScaLAPACK for MPICH2
```

BTW, I would prefer to stay on `debian:8`

**Comment by rschutt** [comment]
Adding MPI seems more involved than this.  Hoping your latest fixes the issue.

**Comment by rvernica** [comment]
It should be fixed now. Thanks for bring it up and for the PR.

Now the `Dokerfile.pre` build log contains:

```
-- ****************** BEGIN src/mpi/CMakeLists.txt ****************** 
-- WARNING-- using locally installed MPICH2 
-- Local MPICH2 path: /opt/scidb/15.7/3rdparty/mpich2 
-- WARNING-- using locally installed ScaLAPACK for MPICH2
```

It required parching two `CMakeList.txt` files in 216e25c7eaf341d6f7cd5af20190b889b70eef17, installing the SciDB mpich2 packages, and updating the `PATH` in [b2459b6](https://github.com/rvernica/docker-library/commit/b2459b6ec2cb4d22a7699bc3de0f6e69c4248fad#diff-11188cf4c5003a0beb7f12d86997835cR92) for the setup script.

**Comment by rschutt** [comment]
Thanks!  I'll try it out.  This is really helpful.  Looks like scidb isn't exactly easy to "dockerize".

**Pull request closed without merging**
